title: CongLeSolutionX
subtitle: My Portfolio Jekyll Theme
description: >-
  This website includes a collection of my projects, resume, and my experieces
  in technology.
url: 'https://conglesolutionx.tech'
baseurl: ""
urls:
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Resume
    url: /resume
  - text: Contact
    url: /contact
author_logo: profile.png
author: Cong Le
author_bio: 'Hi, my name is Cong Le. I built this site using devlopr-jekyll :D'
author_email: congle@swiftandbeyond.com 
author_location: USA
author_website_url: CongLeSolutionX.tech
typewrite-text: This website is a showcase of my projects
hero_cover_img: sample_cover.jpg
author_work_experiences:
  - company_name: Ally Financial
    company_logo: ally.png
    company_url: 'https://apps.apple.com/us/app/ally-mobile-bank-invest/id514374715'
    designation: iOS Mobile Developer
    description: Working on new features for the current bank app
    visibility: true
  - company_name: Intuit
    company_logo: intuit.png
    company_url: 'https://apps.apple.com/us/app/money-by-quickbooks/id1517712685'
    designation: Mobile Software Engineer
    description: Worked on new iOS app called Money by QuickBooks
    visibility: true
author_education_details:
  - college_logo: csuf.png
    college_name: 'California State University, Fullerton'
    college_url: 'http://www.fullerton.edu'
    college_degree: Computer Science
    description: Bachelor of Science
    visibility: true
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: 'https://gamershub.in'
    visibility: 'false'
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: 'https://hack4r.com'
    visibility: 'false'
twitter_username: '@cong_le'
github_username: CongLeSolutionX
facebook_username: CongLeProgrammer
linkedin_username: conglesolutionx
behance_username: null
instagram_username: conglesolutionx
medium_username: CongLeSolutionX
telegram_username: null
dribbble_username: null
flickr_username: null
hyvor_talk_website_id: 476
wakatime_username: ''
mailchimp_form_url: >-
  https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0
formspree_email: congle@swiftandbeyond.com
olvy_organization: devlopr
olvy_widget_type: sidebar
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  products:
    output: true
  authors:
    output: true
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: '/blog/authors/:slug'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
jekyll_admin:
  homepage: posts
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
